### PR TITLE
chore(*): change controller name suffix from 'Ctrl' to 'Controller'

### PR DESCRIPTION
**Pull request by gkalpak**
Related discussion: https://github.com/angular/angularjs.org/pull/163#discussion_r27342489

### CODE REVIEW

**Comment by caitp** [comment]
looks good to me

**Comment by gkalpak** [comment]
@caitp, should I merge this then ?

**Comment by caitp** [comment]
@gkalpak yes

**Comment by gkalpak** [comment]
Hm...it seems like I don't have access to push to `angular/angularjs.org` :confused:

**Pull request closed without merging**
