### PR TITLE
New css styles

### PR DESCRIPTION
**Pull request by alexwolfe**
@petebacondarwin @IgorMinar @naomiblack @jelbourn 

Ok This branch is ready for review. 

## Overview
This is a refresh of the homepage for AngularJS that updates navbar, hero, banner, and typographical styles. 

## CSS 
- Using Sass
- `npm install` then run `gulp` in the parent directory. This will compile the sass and create a angular.css file in the `/src/css` directory. I'm hoping one of you can add this to the build step, I imagine it should be fairly straight forward

## Mobile Styles
- The homepage is now responsive, this should only effect the homepage for now. If you'd like to remove the mobile styles, simply comment out the `@import "mobile";` in the `/src/scss/angular.scss` file and run `gulp`. Poof, their gone. 

## SEO updates
- While added the classes I need to style things I also updated some of the incorrect html elements. For starts the logo is an H1, subtitle is an H2, and all other titles are H3 and H4s so we don't get penalized in search for having a page full of H1s (with no H1 for the name/title of our site). 

Ok please let me know if you have any comments any questions.

### CODE REVIEW

**Comment by alexwolfe** [comment]
P.S. 
You'll notice @2x images, I still need to add styles for retina, those images are for that purpose.

**Comment by petebacondarwin** [comment]
@alexwolfe is it possible to paste some screenshots in here so that people can review the "look" of the changes easily?

**Comment by Narretz** [comment]
First of all, thanks Alex for designing and implementing this!
Here's a screenshot of the new design:

angularjs.org redesign

Mobile 
angularjs.org redesign mobile


A few things come to mind wrt the layout:
- In the main buttons, should Angular 2 be Angular 2.x?, and Angular be Angular 1.x (because it's only Angular).
- In the Angular button, I find the versions are a bit too small. Either they should be removed or made more prominent
- In the "Previous Conferences" block, the headline doesn't have enough contrast
- On mobile, the sticky top bar is very thick. This obscures quite a bit of content

A few technical things:
- the Angular.css file is automatically copied in the build script, so we are good there
- We should integrate the Angular.css file into the docs.css file, so we don't have to load an additional file. We would also load unused styles from the docs.css file. We can use gulp to concat these files.
- For the docs app we need to take out the navbar (and anything else?) styles and html changes and put it into the angular.js repository. This doesn't use sass, so we could simply copy the generated css. Alex could you extract the navbar styles into a separate sass file for this?

**Comment by petebacondarwin** [comment]
Or just Angular :-P ?

**Comment by mgol** [comment]
@petebacondarwin Two buttons: "Download Angular" and "Learn Angular", the first of which downloads ng1 and the second teaches you about ng2+? That doesn't sound like the best choice. :P

**Comment by petebacondarwin** [comment]
Perhaps we should have "Learn the new Angular" and "Download the old Angular"?

**Comment by mgol** [comment]
Thinking of it, wasn't the previous "Try the new Angular" (just without "2") better? It seems to correspond more with "Download Angular 1.x", suggesting that it's something else and not just a button to learn what we download. Also, one button to download the 1.x one and another to learn version 2+ seem out of place; what if I want to learn ng1?

I'd vote for "Download Angular 1.x" and "Try the new Angular".

**Comment by mgol** [comment]
BTW, @alexwolfe, the new design looks so much better than the current one, good job!

**Comment by alexwolfe** [comment]
@mgol Thanks, glad you like the new design. Appreciate the help with the review. I like that suggestion btw: 

> I'd vote for "Download Angular 1.x" and "Try the new Angular".

I think that makes it clear they are different. Let me update this branch and see what we think.

**Comment by alexwolfe** [comment]
@mgol Also, I'll work on addressing the comments you had above and pushing an update today.  Thanks again for the feedback 👍

**Comment by juleskremer** [comment]
@alexwolfe @Narretz  Could we please change the download label to be "Download Angular 1" and the button linking to angular.io to say "Try the new Angular"?  Could we please include a banner underneath the header on all pages of the angularjs.org site that indicates this site and all of its contents are referring to Angular 1.   We are still working on the guidelines that will clean up all of the branding on this site and others: that will be done in a separate PR.

**Comment by alexwolfe** [comment]
Sure, I can handle the changes to the homepage. For the docs and other
pages, I can share a design that should work for a banner like you
mentioned. I'm not familiar with editing the docs template yet, although
I'm sure someone here can point me in the right direction ;)

**Comment by Narretz** [comment]
@alexwolfe 
For the docs app, the relevant files are in the angularjs repo.
The index file: https://github.com/angular/angular.js/blob/c00903be7ac91cd9cd29c265409eea96198b32c7/docs/config/templates/app/indexPage.template.html and the css: https://github.com/angular/angular.js/blob/c00903be7ac91cd9cd29c265409eea96198b32c7/docs/app/assets/css/docs.css

The nav html structure is similar between homepage and docs right now. I think we can work on that after this PR has been merged.

**Comment by alexwolfe** [comment]
@juleskremer @mgol @petebacondarwin @naomiblack 

Ok, I've addressed the comments above, here's a summary of the changes/updates: 
- Improve the contrast on the "Previous Conferences" headline 
- Reduced the size of the top nav on mobile so it occupies less space. 
- Created a style sheet that gets generated with just topnav styles to be used for docs `/css/angular-topnav.css`
- Update the buttons with new text "Try the new Angular" and "Download Angular 1" (versions removed) 

I'll be working on a design for the header underneath all pages that reinforces content on the site is referencing Angular 1 and once this branch is merge will also help assist with stylesheet integration into the docs. 👍

**Comment by alexwolfe** [comment]
@juleskremer Ok, attaching an updated proposal of docs top nav integration and update to current banner: 
angular 1 refresh docs

**Comment by petebacondarwin** [comment]
Thanks @alexwolfe - I think that these docs pages need to make it **very** clear that it is Angular 1.
I would go so far as to say that we should not change the logo.

**Comment by petebacondarwin** [comment]
This also leans more towards the idea of calling Angular@1.x "AngularJS" and Angular@>=2 "Angular". cc @IgorMinar @juleskremer etc

**Comment by alexwolfe** [comment]
@petebacondarwin good catch, yup I agree. I'll update the logo on this branch and the design file to reflect the "AngularJS" in the logo just like the hero banner. Thanks. 👍

**Comment by alexwolfe** [comment]
@juleskremer @petebacondarwin Updated image attached. Update this PR with the correct logo as well 👍 
angular 1 refresh docs

**Comment by juleskremer** [comment]
@alexwolfe the logo is still the new logo, vs. the AngularJS older logo?

**Comment by alexwolfe** [comment]
The logo is the old logo with an updated Shield since the original shield doesn't scale well due to all the extra artifacts (border/lines, extra colors). Brandwise I like this logo since it unifies everything but differentiates the "flavor" of angular with the JS. However, if you're really leaning toward the pure original logo, happy to make the change.  Just lemme know! thanks.

**Comment by IgorMinar** [comment]
@alexwolfe @petebacondarwin it seems that there are many unresolved branding issues still pending.

Unrelated to this PR, @juleskremer and I called for a meeting with Angular Devrel team to create a set of naming / branding guidelines for all things Angular. This will include how to deal with Angular 1 naming and branding (including angularjs.org) and other things like Angular Material.

This meeting will happen early next week when everyone is back in the office. Until then, let's hold any work on this until we get these guidelines. Otherwise we will likely need to redo this again in a few days. Sounds good?

**Comment by alexwolfe** [comment]
Works for me, thanks for the heads up 👍🏻

**Comment by IgorMinar** [comment]
We are now unblocked on this.

- [ ] The official name for all 1.x versions is AngularJS, and for all versions >= 2.0.0 is Angular, can you please reflect this in the PR?
- [ ] AngularJS must be branded using the old AngularJS logo (with borders), we can't use the new logo on the AngularJS site unless we actually want to refer to Angular
- [ ] we'd like a thin strip right under the header (menus) that will say something like "This site and all of its contents are referring to AngularJS (version 1.x), if you are looking for the latest Angular, please visit angular.io." We can tweak the text later, but let's start with this.

If there are more unresolved branding questions, please let me or @juleskremer know and we'll answer them. Otherwise please proceed implementing these changes and merging/deploying them to the production site. thanks!

**Comment by petebacondarwin** [comment]
Also we should use "Download Angular 1.x" and "Try the new Angular" in the buttons as discussed earlier in this PR.

**Comment by IgorMinar** [comment]
@petebacondarwin correct.

**Comment by petebacondarwin** [comment]
@alexwolfe do you have an idea of when this can be finished up?

**Comment by alexwolfe** [comment]
@IgorMinar Thanks for the update and the info. I'll update this today and have the final PR ready for you. 👍

**Comment by alexwolfe** [comment]
@petebacondarwin @IgorMinar Ok, this one should be ready to go. Buttons, logos, text has been updated to reflect AngularJS.

**Pull request closed without merging**
