### PR TITLE
add angularattack 2016

### PR DESCRIPTION
**Pull request by naomiblack**
@petebacondarwin could you have a look and add this to the site please?

image

### CODE REVIEW

**Comment by petebacondarwin** [comment]
:scream: @naomiblack you haven't signed the CLA!!

**Comment by petebacondarwin** [comment]
Oh no, it is @jacquescrocker who needs to sign :-)

**Comment by jacquescrocker** [comment]
@petebacondarwin done!

**Comment by petebacondarwin** [comment]
Oops I just noticed that you didn't change the link! It is still pointing at Angular Connect!!

**Comment by petebacondarwin** [comment]
Fixed

**Pull request closed without merging**
